name: C Release - DJGPP
permissions:
  contents: write
on:
  push:
jobs:
  build:
    name: Build C Release Assets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/djgpp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download and extract DJGPP (DOS cross-compiler)
        run: |
          wget -q https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-linux64-gcc1220.tar.bz2 -O /tmp/djgpp.tar.bz2
          mkdir -p $HOME/djgpp
          tar -xjf /tmp/djgpp.tar.bz2 -C $HOME/djgpp --strip-components=1
      - name: Build for DOS
        env:
          PATH: /usr/bin:/bin:$HOME/djgpp/bin:${PATH}
        run: |
          mkdir -p ./bin
          $HOME/djgpp/bin/i586-pc-msdosdjgpp-gcc -o ./bin/a.exe ./src/a.c
      - name: Upload DOS Asset
        uses: softprops/action-gh-release@v1
        with:
          files: src/djgpp/bin/a.exe
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'autogenerated-${{ github.sha }}' }}
