
name: Go Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release from (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/go
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for Linux
        run: |
          mkdir -p ./bin
          GOOS=linux GOARCH=amd64 go build -o ./bin/test_linux_amd64

      - name: Build for Windows
        run: |
          mkdir -p ./bin
          GOOS=windows GOARCH=amd64 go build -o ./bin/test_windows_amd64.exe

      - name: Upload Linux Asset
        uses: softprops/action-gh-release@v1
        with:
          files: src/go/bin/test_linux_amd64
          tag_name: ${{ github.event.inputs.tag }}

      - name: Upload Windows Asset
        uses: softprops/action-gh-release@v1
        with:
          files: src/go/bin/test_windows_amd64.exe
          tag_name: ${{ github.event.inputs.tag }}
